[build]
  command="yarn build"
  publish="dist"
  functions="functions"

[dev]
  command = "yarn serve" # Command to start your dev server
  publish = "public" # If you use a _redirect file, provide the path to your static content folder
  